replicaCount: 2

serviceType: LoadBalancer

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.8.10.92"

servers:
  - zones:
      - zone: beary.cloud
    port: 53
    plugins:
      - name: errors
      - name: log
      - name: hosts
        configBlock: |-
          10.8.10.90  home.beary.cloud
          10.8.10.91  mqtt.beary.cloud
          10.8.10.40  nas.beary.cloud
          fallthrough
      - name: template
        parameters: IN A
        configBlock: |-
          match ^(.+\.)?prod\.beary\.cloud\.$
          answer "{{ .Name }} 60 IN A 10.8.10.90"
          fallthrough
      - name: forward
        parameters: . 1.1.1.1 1.0.0.1
      - name: cache
        parameters: "30"
  - zones:
      - zone: .
    port: 53
    plugins:
      - name: errors
      - name: health
        configBlock: |-
          lameduck 10s
      - name: ready
      - name: log
      - name: forward
        parameters: . 1.1.1.1 1.0.0.1
      - name: cache
        parameters: "300"
      - name: reload
      - name: loadbalance

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: coredns
          topologyKey: kubernetes.io/hostname

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
