---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCaRnPBsUe2+FkTPg25CIBhn7K+6XtTplNF9CFVCJxYHetSxyYRwciI8RbveNPhbFtAvnzdDM7ZW4/zLZIJo/MmbSmqFl7J+jpbamXI40S/ZJT7+oItni1DVLKWy6VsNMxxCVFgmlQg/wQUpE+YZx1ePyIeshDdywDidvnzNxeg3lt7uVLFWrWg8LQmJjm0n6VvI2Ak18fJLfnnrBpVGRrKOEmPtv47HLUxAexDQhDPJp/ph/KYS7cn2tgLSQU3R2NvPpeHLnvlNbMK8ox2supCFSzbWMza/9pQcSJ9kvb0YjLvkh8UVEvn3PgxMyTV7pHP7z07s6uN2d5I3dIpUJotwzZoggtuqf0un2QsA8h5hyn5zHfJ/TQWrcWIs2PNEpuqM7S17AfqGg+FCsbf9w/qZnj8lrrn77lmQGKrDRiqnmZJOJqiuiFWlSRER+R2zNWeFOUkJ2vKmxcf/spl1G4xmeZLqaLJt94bZsXsEhEDwYA7dKIep2QSlO7AR3FojtlfsZaBYQSYMVjkqTyJg8n5gTxsymeDhCD2mSG1w2pG49YzIHTIXs7Ru+l+rPIV8LDsGt3rgs61pThihthxxmKdh4LDA84e1jNRSI/w5ssJiKvQqXhGv0vMRvDgMWghliQJ2RV42H+Fg/LHmUsXSLI+wdAffpDCi3i3+En4yupFJiGRWitgT9lzA4l0K9RAxnXTO2gKvIKh0uKYQbBPElWsSWZBvEnQGBm/4MnBUE9Y5JGntRayy/0XJ7OXraWlkL+obUZHlctd8zTt8RtlYiTKr4MFH/ljZWtL7clNT9eFvuKChN8ntdgDBRLiwhSY6SFQHaeqeQLKNnqDqf0802nmX69dyjeJTLt38Hsh1nJSewCzusvqNve7UMNHihkPjkMDr5WYzAtXB2C1tm7yvkdQd8adXSq82Sdl8L9vqNPAQdDkU/6T3C2N
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
