---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBRpP7FmOfUu9o/pgpm3altBnYaJi6AjDhvo8QeCdJP7ICKbwdD7zHxUzi6HwNy5AKxh9MddJcYdjxAHfPcMbVMO156I5caunAVWHYjsUP6qJKKxh0+nAC6EwoVdK6FQXwvh0ZIWK155spkPciVdNrhJ4JnGqrGa9PqMHgf/d8y6cnf7eDumHXl6nD63qfbujPdcFDx+RqoJ+gb67JgpVVo9pVBxTIUEiVAS86MHzJ8NwT1m9PFEf6MCtSxXt5jXL4Szyy84riPzmgF50T2C3zIEv3DcmD9RmsUXZ7BJiukhmDQvgvqGJ4FmmStnzZpB4C3tk4n6n1h9IF2XYeK09NxGE0RuNiC+11gknMm65U0UObxB5UOgbsViz4WDGcp3Zxhud8dwIBC25Q1Vbf2zYGB2IX0ca7y2It5Rli5R6niE9dpnC1w0RovDgLnB0t5FYsNFV3gfl9CUmqCJhfYu2uOWslbGaz5fvM4d5OlhBoliRw10yEEsRaptO65BEr35/HiLxc2t+R/voRXdO2cLdzfnjpPzGxW6VO0Ucs3UZKlBn+uto2WQaVDe/eziF+3ch3VYQvcGlkwrtjAcy1KCy+9goUPOoX9wTb54Wmk3gZRgoFoyOIuYugExJFL+z6TYQVcB+TXiIfcecxCG6LqfuaqhkQuZl0yBh7MwH2YPGoQKDlz9xRj20iV0H6jacqeJRK+pifZyf7HDO8KuvsRRuSOYLrjhxjmHtaT0EOY/cQAxGCk8uU28ax+Ilp5VdotGdF613jy8Hc4VAg+f1562pATZX/B70ihSqP/U5Ahqnzcq8htIL6HOBT0Ue8/NKEvCgQt48LEu5syr5Q4mEGwe9AWYt1u85M3WaJsTNGwSBObfVXVpSXXXWHAyjpmTBt6nDY2/O8s1EhTyO+97xsiAbY0aNLXKNOre1wsuoq6ah+VKr0BHaKoVdZy
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
