---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBILh4MPwj7BClqFxwBggcuFLZDAqkXv1xel8jb53I5bM0Ld1tdcPY8lEgC5ZlQEkF/2v6ciT4REKNN0/4mXh/pUOKjQbt/sl9ZcdEzfxokT0sasVogxbQDgO5xsdBf6YHYvKgumln4aPFjj1wPun09tF2IaoF8AjiT05EMYHYAs13kKWjNSQDtMGA4BmNKvzeLUTf9CekB/u7tQZTwkcGODpqx2/DU/NKsAYZvYpu7Jl6NPzqYUxaWSZnSwbkPRLO0/dtTRcJXNdffVWRJbGT+LGvfb3a0PJUoKdiXPN83QAlBOXJ104fgB9sod8nkd+SWrLEdC7uXGrfyuWKbVvctHBomPz4EZ/6yjoY7yXn7przDfOULGTRcV3Vh8n0TcdYiw/ClH5Z6otQ+zmQD3Gr2qca2EEzg84q8uIEX1ZxeoPMcwb9Xv6SQoSnWe79ttIRD5yEptsHHUUj6f2X6/BWiOAz/VFLtT6mAclg2jSPSuxukHrGWh9u0sVKlfdhizmLr58vWK3azfrVSPZbSwPRFToFpB3wDRmMv1ZBenh2GYKo0qn0o/yw6qRKKpB1nGlfB1teye/tLO3XLe8Io6gEVtOkKLjn24MSiEZ0zHQNaqvndRqo/sIJT5jNXiEdIOAPjtXUjmOXRKQ8BnXi+NCww4hCz8vAsMMU4VYLUYReXxk0uXdM/UXPy5VVerppH6BC2PeZMH6sI6eVw+i51AuyAD/FApW0HLdIxtcCG9t1Ucst5X5Nb2+nHDJDt2UY0LVMlKjQyYJri2XWuyyK3yR168KLwYwMGBRTNoNdHq0wvhrcUhVqiI+r9sxtPlUoQ09Y/g1qJEuPclFPOWk/FwUaSADFF1TouHCI/66VuShG6SQgZb+N9pKqG0pRfEgf574W356DF1DEhMnB1DMliO1jOLEOSZYnDquUx4uBCamSloXieDNc/eCRr
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
