---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBrvV5WmPl8dpT2dE9l/zH3BJ4OqaShBcqhVQY1hq6rbMN9XgSy7nuzauPk97QDxckeukqAQ5ymWhG5FrBxMjNBymv5mVRD34iIuF0EF04i12FpJhPgP8vy85cWEQg6h4JEMP9L0a9L9awMYlXpznt88R7bpfcNX7k5geUgQSfognXvSRB4GrbanbnCWw9TxL1BmJ8x8gbU4j7wGTxZA98qVx8x7I356Y5ZeLHJZpbkxqq9CnepG++BHH5/JM8rCdTy50Kukk5RcYqTNFlagmuwS+cSFB3SX+044Bdkw9u2t1FHuOtll2z1rMyKoQPgU5OmDz75Ejhe06GfvtqZzak7D6eZaqiMDcn0yii9ppnp6KsICziPrFSwfTpnnWtl4QbEh6mMrG8RUZdgJji0GUROq4/3dQXiqhreU/HAeniAu/cgSVo8U5ckFzJyN85FwhvewuSTCC/rPRYC/2PBCJCLEqNXUJCyU5WmPipluMUkyRscQbK7/q1NsLOe9wcBQIAfrPN3MPHiEmg9KPuvsb7l0tBwDNEUvMr1WnN4I9i6iGW/zrym0soOZlfVtp3JOis6Jp/JeSUd7oDzZXu3vZYDSruvypEBVVyzhkhm4zDuWAE3Bzqqy0PdOCtGTZld6dPLFnBnrC7/7Qgn601oMufAymUyfWFC+2VoNS0xWpZli6bt/0DsXQGWswgW5GFGGLyOXYFotJYkM7Qxm/4GHR0QzCRISapmVF+eXfvQKKP98iHRU8b5BlsPQk6t2NQQEn3iU+/6w7GO6EKhGUAlprmKeC5b3/fAqqYZXC6aciseyhPyvGkQSQkqgn8lnN3BHvz4AZZLbuFCg1UZRTbAdvokds5twWc7tPxj2l67Uq4kMLTCLZpzTWDIMjbCKvBEutpsRnUX1g9EFQLfUvdOEYooRQXhtPh+OAwcrYS9SPKdC3LabvPHvPIO
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
