---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBIfEfbC6bMihLDStSgHacGiFCuhNbGtkCoQINWxLzr3Gn8B+KSfBhcForIB2gUK+dlOCMNnVpXxMl5F5e5C4LPU85PtPy2hwnoZF6W4WUd3hWqGaGfcSs8Z7z118gT2bfnmb67MfX4NH++5br1OqtsWy3Fji+5m/xX0XEBmIeo3JzlGBV/y8DWwXZpyQSs7k5SKd6KY8Y7kV7A8smf4GzvzC08BMXncA/NpUM6lOaCdXDKEkHXyuIhD/Cz6D3BMgeN8Yjw11/mlC9zviyUg/ssQQBsiTOOeX/WG5iRGe4SYK2jjdHJc6k24J8nSioaZN2Pc3YlE5pQDy/7fMyu5t2qo+03QgKQEs6uWQuvlXhrfJMuvYPwG/ExgP2QMhV7yy+23GEglCpze2fClCIJJnvsfRSgGXlCyP8Rh4wB/Bj6v/cVAmh1Pk0PtWZD6Xf+g/C6pXq0DahQNQrkpT4/1/uqBub86yMcGuzF2qYbdi3m8s0/W9ezRX5VLA7Aw6XGX9cSMcxfIu/H6YTHlXtwUvO4QJ2rinu8eUo/0cKHeaLiAj15hGUQRZe44VcumyKRmaSNOErtrbkwkzwMGwnuM/7h55GLGTOXZLMZq+hXQBz38d4E/mVC+gAKi6I05eMF1fMrOrzIQsduO2gka/HwyWRaTr0G/ZJ3tpvE2Dp0N3sNZvw4LAmQoyu5buBR4pzdWv/3ipWlTpBxlE6bSKN00EMPu2Je0fHXXQCFrmLZvBCiVU26HJYEgQqAc6cjyZH8O2xtPH5k7Q==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
