---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCuiIVyJuXyjcmKCnH8gyzsQh3XTH0bTrSNbcstoE6JkJz95W0TgxaRiknmhDKzcNCyCbZBuo2a6JOQ7MFWwNnCzAPwQe9H6YANHVXBGfBNH9+WH/O5m4edSOszr0e/NLv3sozdrlG2kwZRGV04P/j9ARltdyRzfjIrn4lenMvQ/1UNKBbH9yZRNoRnoAzdggpBEQWh6mqDctM6f9L61GQm9IOsNsAJ5I+nmNbqAK2IVujgLDNR1UvDKMQtox4lclA8aF4nvOHr3g7U10wSkEUUMRi1184CuzbPl14hcIe8vlTlHDuv7XK1Fd1e3Zf9LPQPUNC7eQDh9BGVCv69ULdQ6b57z+Ds/XcjUxvKUSq4EavEa1+k7E7/Ihqjlw0A5pUr8Yq7MSlVQ5cDQQpVWKmC2sd5+d2s+YywgsJWbLJC+moqjMv2lSKnfyGB8xyUW0hMkeM0gBE0CbVrgVgor/Is0ypNdIM7hW5bI1tgJYPnkArDVN0fqjFVyaVXYxR9Kz4LG/aFpRDOcJz9/+O7BVQVkizsxxidYOTRMej4P7Sc6G9tedhP/QuvsOLaICGZJxEhOEX0JpShbatSyTJvIcLpw9/inS+Rc4Txkl8M++moDgWLbitbBS8uj1/QOYQtce5bNw2M87mvQ1TLvIhfUpg9VNpc4o6RXYIjutde5B7PRhqLhuRQHYPTSQj6Xc/4ZBcXrBNO3kkmmT9Dv0vh2YVDO395f4dTQMWzKUjeMLVCdz3Qk19frow2WLPQBc51Rh3qjQDCeA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
