apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 3.7.3
      helm:
        valueFiles:
          - $values/kubernetes/apps/dus-prod/cloudflared/values.yaml
    - repoURL: https://github.com/bearylabs/operations.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/bearylabs/operations.git
      targetRevision: HEAD
      path: kubernetes/apps/dus-prod/cloudflared/secret
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
